SSWConsulting/SSW.People

- src/components/checkbox/checkbox.js
- src/style.css
This list is too long, and it goes beyond the actual employees' area:
I see no reason for having these items in bold either.
> updated css to improve skills filter look and feel

- src/components/footer/footer.js
- src/style.css
Closes issue #334.
Added social media icons featured on the Consulting website into the footer of People.
Figure: Social media icons in footer. QR code appears when hovering over the WeChat icon.
> 💄 Add social media icons to footer

- src/templates/person.js
- Moves the widget positioning on Mobile Devices to under the GitHub Contributions. 
- Fixes a bug when at a certain  screen size the rules widget would disappear 
FROM:
**Figure: Widget overlapping with text and creates a big gap between the content**
TO:
**Figure: Widget on mobile devices moved to under GitHub Contributions.**
> 🚸 Fixes Widget Positioning on Mobile devices 

- src/components/footer/footer.js
- src/components/skills-list/skills-list.js
- src/style.css
cc: @adamcogan, @tiagov8
Hi Tiago,
As per our conversation I have restyled the Peoples footer so that it is consistent with the Rules footer. 
**Figure: current People footer**
**Figure: Updated peoples footer**
**Figure: rules footer**
I could not find an equivalent to https://github.com/SSWConsulting/SSW.Rules/releases/tag/20201117.1 for people so I did not add a link to the build version. 
You will note that in my updated version the build version number has been replaced with "#(VERSION DEPLOYED)" I have not made any changes to cause this so I believe that it is due to my local branch. (I consulted Jack P and he agreed)
> 424 style make footer consistent with rules footer

- .gitattributes
- .gitignore
- .yarnrc.yml
- gatsby-config.js
- package.json
- src/style.css
- yarn.lock
fixes #499
- adds compatibility for devs using modern yarn (adds classic shim)
- badges - fixes issues rendering rectangular badges
previous code would always render badges at 100px high - even though 135px high images were supplied
> Fix badge rendering

- src/style.css
> 💄 CSS - Prevent SVG badges from rendering super large

- gatsby-node.js
- src/components/profile-box/profile-box.js
- src/components/profile-list/profile-list.js
- src/helpers/CheckUniqueName.js
Relates to #534 
Changes made:
- updated redirect rule: remove the shortcut if there are two same names
- deleted incorrect redirect key/value
> 🐛 Fix Redirect Behaviour

- tailwind.config.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1262
Updated tailwind.config.js to make JSX file be covered by tailwind globs
UI changed from
To
Better consistency with Website and Rules 😉!
> 💄 Updated CTA Form UI

- src/components/profile-description/profile-description.js
- src/templates/person.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/309
Added tag+icon next to the title on past employee's profile **(only for screen > 640px）**
> 💄 Make Alumni Status Obvious

- Readme.md
I noticed this repo looks bad on Google search.
I am guessing Google looked at the H1 (SSW.People) and didn't like that it didn't look like readable words.
**Figure: Ugly search result**
> 🔍️ SEO - Try fix the google search results for the GitHub repo

- src/404.css
- src/style.css
Relates to https://github.com/SSWConsulting/SSW.People/issues/610
Fixed duplicate h1 selector overriding each other
UI changed from:
To:
> 🐛 Fix Global CSS Collisions

- src/helpers/CRMApi.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/373#issuecomment-1958500417
In this PR:
- Reimplement the filter feature for People to only show skills with consulting pages
> ✨ Filter Out Skills Without Consulting Pages

- gatsby-node.js
- src/helpers/CRMApi.js
- src/pages/index.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/347
Changes made:
- Sort skills based on highlight flag and then by number of people
**Figure: the `Highlight skill` filed is set to true for both Blazor and TinaCMS when I took the screenshot**
> Skills List - Sort by highlight and number of people

- src/style.css
There's an underline in the Megamenu on live site so I've created a PR for fixing it.
- Fixed: #659
> 🔥 Hotfix - megamenu underline on mobile layouts

- gatsby-browser.js
- gatsby-ssr.js
- package.json
- src/style.css
- yarn.lock
Relates to #697
This pull request includes updates to replace the `@fontsource/inter` package with `@fontsource-variable/inter`.
The same fix was done to SSW.Rules - https://github.com/SSWConsulting/SSW.Rules/pull/1623
> ♻️ Inter Font - Added preload to avoid FOUT issues

- src/style.css
Fixes #701 
Increased `z-index` value of megamenu on SSW People, because it's value was same with profile photo button. That's buttons were showing
**Figure: Profile photo buttons are not showing when menu is open**
> Increased z-index value of megamenu

- src/pages/index.js
This PR adds an alphabetical sort before the additional sorting to make it easier to find skills https://github.com/SSWConsulting/SSW.People/issues/632
Current sorting in SSW.People | Skills side bar
This PR sorts these alphabetically instead
> #632 - Added alphabetical sort to skills side bar

- src/style.css
Fixes https://github.com/SSWConsulting/SSW.People/issues/735
Now functions the same as https://www.ssw.com.au/
**Mobile view with hamburger menu**
**Menu opens and appears above everything**
> 735 - Add CSS styling to fix the z-index of the megamenu

- src/style.css
Fixes the custom image blocks not adhering to the size constraints
https://www.ssw.com.au/people/bob-northwind/
**Before Change**
**After Fix**
> Fixed CSS for custom image block sizes

- package.json
- yarn.lock
Fixed: https://github.com/SSWConsulting/SSW.Website/issues/3971
**Figure: Mobile Megamenu closing properly on SSW Website staging**
> ⬆️bumped megamenu to 4.12.0

- yarn.lock
Bumping multer to 2.0.2 as dependabot currently unable to access build secrets
---
updated-dependencies:
- dependency-name: multer dependency-version: 2.0.2 dependency-type: indirect ...
> Bump multer from 2.0.1 to 2.0.2
