SSWConsulting/SSW.People

- content/home/intro.md
- package.json
- src/components/header/header.js
- src/components/location-filter/location-filter.js
- src/components/profile-box/profile-box.js
- src/components/profile-list/profile-list.js
- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/constants/transition.js
- src/helpers/arrayHelpers.js
- src/helpers/locationSort.js
- src/helpers/roleSort.js
- src/helpers/valueHelpers.js
- src/pages/index.js
- src/style.css
- src/templates/person.js
- yarn.lock
- Add skill and role filter checkboxes,
- Move location filter to top
- Style the page following the new design
> Ui new design

- gatsby-config.js
- package.json
- src/components/checkbox/checkbox.js
- src/components/footer/footer.js
- src/components/layout/layout.js
- src/components/location-filter/location-filter.js
- src/components/profile-box/profile-box.js
- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/helpers/arrayHelpers.js
- src/pages/index.js
- src/style.css
- yarn.lock
Add footer with build version and style following SSW home page
> Add footer

- .azure/azure-pipelines.yml
- .gitignore
- Readme.md
- gatsby-config.js
Update deployement yml to create environment file needed in prod
> Change the environment file required in production

- src/components/role-filter/role-filter.js
Change role filter display to 'RoleName (x)'
> 47612 improve category display

- src/components/location-filter/location-filter.js
- Change background color to grey
- Change text color to black
- Change selected text color to red
> Location filter improvement

- src/components/profile-box/profile-box.js
- src/style.css
Number of profiles per lines grow dynamically with screen size
> Number of profiles per lines grow with screen size

- src/style.css
Changing font-size and Bolder 'Our People'
Fix vertical-align of the title 'Our People'
> Improve display of 'Our People'

- src/templates/person.js
Stack Profile photo column on top of profile
Large screen:
Change column size ratio
> Improve profile page display on mobile and large screen

- src/components/layout/layout.js
- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/pages/index.js
- src/style.css
Add margins on main layout 
Add hover on filters
> Add margins on main layout and hover

- content/home/intro.md
- src/components/role-filter/role-filter.js
- src/helpers/locationSanitizer.js
- src/helpers/locationSort.js
Add header to 'Roles' filter
Change 'Elsewhere' to 'Others'
Add line break and modify intro text
Reword to 'Read on to meet us'
> Index - Design changes

- src/components/checkbox/checkbox.js
- src/components/header/header.js
- src/components/layout/layout.js
- src/components/location-filter/location-filter.js
- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/pages/index.js
- src/style.css
Role and Skills filter switch to a droplist on mobile
> 47905 fix display of Index page on mobile

- content/home/intro.md
- src/components/header/header.js
- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/pages/index.js
- src/style.css
Fix margin on mobile
Fix header margin
Delete This is not live data
Improve filters layout on mobile
Handle click out of droplist
Close on clear
> Fix display on mobile

- src/style.css
- src/templates/person.js
Move name and position on top on mobile
> Improve Position area

- src/components/location-filter/location-filter.js
- src/style.css
- feat(48067): add location filter on hover styling
> feat(48067): add location filter on hover styling

- src/components/footer/footer.js
- src/components/head/head.js
- src/components/layout/layout.js
- src/style.css
- feat(48080): footer to be full width
> feat(48080): footer to be full width

- src/style.css
- src/templates/person.js
- feat(48090): change global font family and css cleanups
> feat(48090): change global font family and css cleanups

- src/style.css
- feat(48114): image link should not have dotted border
> feat(48114): image link should not have dotted border

- src/style.css
- src/templates/person.js
Remove semicolon from skills and also change it to `|`
> feat(48165): remove semicolon from skills

- src/components/role-filter/role-filter.js
- src/components/skills-filter/skills-filter.js
- src/style.css
- src/templates/person.js
> feat(48163): office location info redesign

- src/style.css
- src/templates/person.js
Move Edit and Info links to the right on mobile
Fix align on large screens
> Move Edit and Info links to the right on mobile

- src/templates/person.js
Fix skills separators
Advanced skills are bold
> Fix skills separators

- package.json
- src/components/contact-form/contact-form.js
- src/components/contact/contact.js
- src/components/header/header.js
- src/style.css
- src/templates/person.js
Change target of 'Edit' and 'Info' buttons to '_blank'
> Change Edit and Info link target

- package.json
- src/style.css
- yarn.lock
> Change the font size of the breadcrumb

- gatsby-node.js
- src/helpers/profileSort.js
- src/pages/index.js
Previous employe generated in previousemployee/
Add optional custom URL field
> Add support for custom URL

- .azure/production-pipeline.yml
- .azure/staging-pipeline.yml
- gatsby-config.js
- gatsby-node.js
- gatsby-ssr.js
- package.json
- postcss.config.js
- scripts/favicons.js
- scripts/lighthouse.test.js
- site-config.js
- src/helpers/createRewriteMap.js
- src/helpers/plugin-data.js
- tailwind.config.js
> added lint script to staging pipeline w/zero warnings

- gatsby-node.js
- src/components/profile-box/profile-box.js
- src/components/profile-list/profile-list.js
- src/pages/index.js
- src/templates/person.js
* Changed files to use nickname as default URL and part of the name
* fixed ESLint warnings
> Changed files to use nickname as default URL and part of the name (#112)

- gatsby-node.js
Reduce size of previous employees folder from 600MB to 120MB
> Create page only for md files

- src/components/youtube-playlist/youtube-playlist.js
Reduced number of video thumbnails when playlists were less than 3 videos
> less video thumbnails when under 3 videos

- src/components/event-list/event-list.js
- src/helpers/eventHelper.js
- src/style.css
Add past talks button to display past talks of an employee
> 51801 add past talks

- gatsby-node.js
- src/components/github-contribution-calendar/github-contribution-calendar.js
- src/components/play-audio/play-audio.js
- src/components/profile-box/profile-box.js
- src/components/skills-filter/skills-filter.js
- src/helpers/createRewriteMap.js
- src/pages/index.js
- src/templates/person.js
PBIs
#51526 https://ssw.visualstudio.com/SSW.People/_workitems/edit/51526
#48710 https://ssw.visualstudio.com/SSW.People/_workitems/edit/48710
> Change code to load information from the new CRM API

- src/components/event-list/event-list.js
- src/components/profile-list/profile-list.js
- src/helpers/profileSort.js
- src/pages/index.js
- src/style.css
Order by Rate and Position
Display tile 'We are hiring' on every locations
> Past talks

- .azure/production-china-pipeline.yml
> Set up CI with Azure Pipelines

- gatsby-node.js
- src/helpers/skillSort.js
Read the field Sort Order from CRM to order the skills on the profile page.
Sort by:
Advanced/intermediate
Sort order ASC
Alphabetical ASC
> Use Sort Order to sort skills

- gatsby-node.js
- src/helpers/CRMApi.js
- src/pages/index.js
- src/templates/person.js
This reverts commit 2558375d80295abf63f8d25569e1ca76858022c2.
> Revert "Read Audio URL from CRM (#245)"

- .azure/staging-pipeline.yml
> Update staging-pipeline.yml for Azure Pipelines

- content/home/intro.md
as per https://devblogs.microsoft.com/dotnet/introducing-net-5/
> From .NET Core to .NET

- .azure/staging-pipeline.yml
- .azure/templates/build.yml
Fixed run condition on test task.
Tests only run on the main branch
> Fix pipeline build issue

- .azure/production-pipeline.yml
- .azure/staging-pipeline.yml
Added workspace clean before jobs run
> Fix pipeline build

- src/style.css
> 💄 Center social icons

- src/components/footer/footer.js
reordering social icons - Marketing team request
> reordering social icons - Marketing team request

- src/style.css
Added the red hover and underline styling to links
See the following for reference
https://www.ssw.com.au/people/
https://www.ssw.com.au/people/adam-cogan
> Added color and underline styling to links

- src/pages/index.js
**Figure: Selecting multiple skills only shows people with all selected skills on their profile**
> changed logic from OR to AND

- src/style.css
> Geordies styling changes

- src/style.css
cc @JackDevAU @bradystroud @Geordie88
> Making list style changes apply only to content

- src/helpers/CRMApi.js
Currently SSW.People shows deactivated skills from CRM. 
This PR fixes the issue by only showing active user skills from CRM.
> Fixed filtering of user skills

- src/style.css
This PR changes the nested lists styling that is currently broken in staging 
From:
**Figure: SSW.People - Nested lists on staging**
To:
**Figure: Fixed styling of nested lists with this PR**
> Fixed styling of unordered list items

- SkillUrlData.json
Resolves #406 
- Added .Net to fuzzyMatch in SkillUrlData.json file
> Refact: Added .Net in fuzzyMatch to get Web-Applications page url

- src/components/skills-list/skills-list.js
- src/components/youtube-playlist/youtube-playlist.js
- src/style.css
Reverts SSWConsulting/SSW.People#416
At Tiago's request please revert :)
> Revert "Style - added extra hr row between skills and logos + restyled view a…"

- src/components/youtube-playlist/youtube-playlist.js
Added 4px of top padding to the view all link
figure: new layout
> 💄Small style change- added padding to link #414

- src/pages/404.js
just tweaking the text at Tiago's request
> ✨ 404 page #419 - edited 404 text

- src/components/footer/footer.js
Small change that should fix the mixed content for the people sub site
Fixes #436
> 🐛 Fixed WeChat url to be https

- src/templates/person.js
> 🔥 Comment out contributions error

- Readme.md
- lib/ssw.megamenu/data/menu.json
Trying to fix the not secure issue
> 🔒 Replace http links with https

- SkillUrlData.json
Resolves #445 
- Added Home/Office Automationto fuzzyMatch in SkillUrlData.json file for [consulting page](https://www.ssw.com.au/ssw/Consulting/Smart-Office-and-Smart-Home.aspx)
> Refact: Added fuzzyMatch to get Smart-Office-and-Smart-Home page url

- src/pages/index.js
As per my conversation with @adamcogan, we will be commenting out the extra sorting as a temporary fix to the issue https://github.com/SSWConsulting/SSW.People/issues/456
> fixed user names not matching with their correct image

- src/style.css
- yarn.lock
#459 
https://www.loom.com/share/7ef1cb3d44104463a7b63318bbf3c272
Approved by @jaydenalchin
> 🐛📱 459 Image responsiveness

- static/robots.txt
#467
Fixing the URL for the sitemap in robots.txt to fix SEO issues
> 🔍  Fix sitemap URL

- .azure/staging-pipeline.yml
- .azure/templates/test.yml
- .github/workflows/ssw-people-scan.yml
https://github.com/SSWConsulting/SSW.CodeAuditor/issues/427
---
cc @william-liebenberg  @adamcogan 
As per my conversation with @tiagov8, we would want to add a scheduled scan for SSW People every Wednesday
Hi @christianmorfordwaitessw 
Before approving and merging this PR
1. Can you add a NEW secret for `CODEAUDITOR_TOKEN` in this project
> Add scheduled CodeAuditor scan

- package.json
- src/templates/person.js
- yarn.lock
Fixes https://github.com/SSWConsulting/SSW.People/issues/486
Changes:
- Updated the widget
> 📦Update Rules.Widget

- .github/workflows/ssw-people-scan.yml
https://github.com/SSWConsulting/SSW.CodeAuditor/issues/455
> Updated CodeAuditor scan command line

- package.json
- yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Rules.Widget/issues/33
> 📦 Update Rules Widget Package

- package.json
- yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Rules.Widget/issues/36
Changes:
- Updated widget version so that we can use back the github api
> 🐛 Fix Missing Latest Rules

- src/templates/person.js
Changes:
- Fixed widget import error
> 🐛Fix Widget Import Error

- static/manifest.json
- Adds a manifest file to `/static` to fix CodeAuditor 404
#480
> Add Manifest.json

- package.json
- src/templates/person.js
- yarn.lock
Relates to https://github.com/SSWConsulting/SSW.Rules.Widget/issues/39
Widget Upgrade:
- Fetch data from commits.json instead of the Github API.
- Add a "See More" button below the widget list.
> 📦Upgrade Widget

- .vscode/settings.json
- gatsby-node.js
- package.json
- src/components/profile-photo/profile-photo.js
- src/components/profile-utils/profile-photo-utils.jsx
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/profile-utils/utils/ProfileImageDownload.jsx
- src/style.css
- src/templates/person.js
- tailwind.config.js
- yarn.lock
https://github.com/SSWConsulting/SSW.People/issues/507
Included in this PR:
- ✨Copy button to copy employees info as HTML to clipboard
-	NOTE: This works for any application that can paste HTML, i.e. Word & Outlook
- ♻️ Refactor Profile photo
- 💄 Update Tailwind colors
- ✨ Add billingRate to CRM query
- ✨Add vscode format on save setting
**Figure: Info copied to clipboard**
**Figure: Add a copy button**
**Figure: On click/copy button will turn red for half a second**
> ✨ Copy Profile info

- package.json
- src/components/layout/layout.js
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/style.css
- yarn.lock
PR Adds the following, 
- New dep `react-hot-toast`
- `Copied to clipboard` toast on click
- removes onClick 500ms hover effect
- new hover effect 
**Figure: toast when clicking "copy"**
> ✨ Add toast + hover effect to copy profile

- src/components/profile-utils/profile-photo-utils.jsx
- src/components/profile-utils/utils/CopyProfileInformation.jsx
Adds 
- New copy format (Uses table and no longer uses base64 image)
- Ensures billingRate is a number (there was a possibility that it could be a string before)
- Slight refactor of the HTML and image code  
**Figure: New compact format**
> ✨ new format + reduce code

- src/components/profile-utils/utils/CopyProfileInformation.jsx
https://github.com/SSWConsulting/SSW.People/issues/507
- Update formatting to follow @tiagov8's suggestion 
- Change the way the url is being created 
From:
**Figure: Old formatting** 
To: 
**Figure: New Format**
> ♻️ change formatting

- src/components/profile-utils/utils/CopyProfileInformation.jsx
Adds some debug logs around `location` and the profile image object
> 🔊 Add logs

- src/components/profile-utils/utils/CopyProfileInformation.jsx
Attempts to fix copy image path
> 🩹Profil copy feat -  fix image path

- src/components/profile-utils/utils/CopyProfileInformation.jsx
> 🔇 Remove logs

- src/components/contact-form/contact-form.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/523
Changes:
- Updated create-lead endpoint of "Contact-Us" form
- Modified the payload
> 🐛Replace old form endpoint and update the payload

- gatsby-node.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1089#issuecomment-1705848698
Changes:
- Added path without slash to the rewritemaps.xml
> 🐛 Fix People Redirection

- src/components/contact-form/contact-form.js
Fixes https://github.com/SSWConsulting/SSW.People/issues/530
> 📝 Add Doc Reference For Creating Lead

- package.json
- yarn.lock
Relates to https://github.com/SSWConsulting/SSW.People/issues/532
> 📦 Upgrade SSW.Megamenu to 3.2.2

- src/templates/person.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/475
Changes made:
1. Changed rule count to 5
> 💄 Limit Rules Shown to 5

- src/components/footer/footer.js
Related to https://github.com/SSWConsulting/SSW.Website/pull/1452 and https://github.com/SSWConsulting/SSW.Rules/pull/1111
> Made copyright info standard

- src/templates/person.js
> 🐛 💄 UI - Improve profile margins

- src/templates/person.js
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1046#issuecomment-1757259373
Updated the 'See More' button link to go to the most recent User Rules page
> 🔗Update "See More" button link

- src/components/action-buttons/action-buttons.js
- src/components/header/header.js
- src/components/profile-description/profile-description.js
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/profile-utils/utils/ProfileImageDownload.jsx
- src/components/youtube-playlist/youtube-playlist.js
- src/style.css
- src/templates/person.js
Fixes for the following items, 
- https://github.com/SSWConsulting/SSW.People/issues/546
- https://github.com/SSWConsulting/SSW.People/issues/544
- https://github.com/SSWConsulting/SSW.People/issues/548
- https://github.com/SSWConsulting/SSW.People/issues/545
- https://github.com/SSWConsulting/SSW.People/issues/550
**Figure: View all moved to bottom**
**Figure: Contact box now spaced evenly**
**Figure: Added a hr**
**Figure: Fixed language selector** 
**Figure: Fixed copy + download button + red buttons instead of black**
> 📱 💄 Fix mobile styling

- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/profile-utils/utils/ProfileImageDownload.jsx
- src/style.css
- src/templates/person.js
Fixes to @tiagov8 comments
- https://github.com/SSWConsulting/SSW.People/issues/544
- https://github.com/SSWConsulting/SSW.People/issues/546
- https://github.com/SSWConsulting/SSW.People/issues/550
> 💄 Fix styling issues

- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/profile-utils/utils/ProfileImageDownload.jsx
- src/style.css
Styling fixes for,
- the download and copy button
- Change tooltip as per @jaydenalchin suggestion
- https://github.com/SSWConsulting/SSW.People/issues/550
**Figure: button alignment fixed**
> 💄 fix style

- package.json
- yarn.lock
https://github.com/SSWConsulting/SSW.People/issues/546
-  Updates the `ssw.rules.widget`
- `^1.6.0` -> `1.6.2`
> 📦 update widget version

- src/components/layout/layout.js
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/profile-utils/utils/ProfileImageDownload.jsx
- src/templates/person.js
Small Fixes, 
- https://github.com/SSWConsulting/SSW.People/issues/550#issuecomment-1773057588
-  revert to "Download photo" and "Copy details"
- https://github.com/SSWConsulting/SSW.People/issues/558
- adds padding in small view 
**Figure: added padding**
> 📱 Styling Fixes

- src/components/checkbox/checkbox.js
- src/components/filter/filter.js
- src/pages/index.js
- Refactors count + skills in the side category/filter 
- Fixes side category/filter list 
- Adds full width to the category for better UX 
- Adds scroll to top on click of category 🚀
> ♻️ Refactor code to improve performance and readability

- src/components/skills-list/skills-list.js
- src/helpers/CRMApi.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/583
Comment out the skill filter so that skills without a link to the marketing page can still be present on the profile page
> 🐛 Fix skill display issue

- src/components/contact-info/contact-info.js
Latest scan on CodeAuditor detected phone numbers not in hyperlinks
- Minor change to include phone numbers in hyperlinks
To comply with rule https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers/
> Fixed phone number not in hyperlink

- src/helpers/CRMApi.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/585
Changes:
- Filter out archived skills
> 🐛 Remove Archived Skills

- src/components/people-filters/people-filters.js
- src/helpers/eventHelper.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/346
Changes:
- Refactored the code to display correctly the list
- Hide the speaker list if it's empty
> 🐛 Fix Empty Speaker List

- src/components/footer/footer.js
- src/style.css
- Updated footer icons style
- Removed Wechat
- Added Tiktok
**Figure: updated icons.**
https://github.com/SSWConsulting/SSW.People/issues/447
> Updated footer icons to match SSW Rules

- gatsby-node.js
- package.json
- src/components/profile-box/profile-box.js
- src/components/profile-list/profile-list.js
- src/pages/alumni/index.js
- src/pages/index.js
- yarn.lock
Relates to #562
Changes:
- Use fullname as default in the URL
- Update rewritemaps.xml: link using nickname can now be redirected to link with full name
- Upgrade `sharp` to the latest to fix errors when running `devbuild` locally
> ♻️ Set fullname as default URL and updated RewriteMaps

- gatsby-node.js
- package.json
- src/components/header/header.js
- src/components/layout/layout.js
- src/style.css
- tailwind.config.js
- yarn.lock
Relates to https://github.com/SSWConsulting/SSW.People/issues/594
> Added new megamenu

- package.json
- src/components/header/header.js
- tailwind.config.js
- yarn.lock
> fixed megamenu styling when using a mobile device

- src/404.css
- src/pages/404.js
**Figure: Desktop view.**
**Figure: Mobile view.**
Closes #502
> updated 404 styling to fix resize issues

- src/components/contact-info/contact-info.js
- src/components/contact/contact.js
- src/templates/person.js
relates to https://github.com/SSWConsulting/SSW.People/issues/389
> changed call to action text for alumni users

- src/components/contact-info/contact-info.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/389
> updated alumni cta

- src/style.css
Relates to https://github.com/SSWConsulting/SSW.People/issues/616
> 💄UI - Fixed Missing Underline

- src/components/profile-utils/utils/ProfileImageDownload.jsx
Changed tooltip
from
Download Photo
to
Download colour photo
> Updated profile image download button tooltip

- src/components/profile-list/profile-list.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/634
Added skill filter to the top of the profile list. See below:
**Figure: Filtered 1 skill**
**Figure: Filtered many skills**
> 💄 Show Skill Filter to Top of Profile List

- src/components/profile-list/profile-list.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/634
Example:
From 
Azure-App-Service
To
Azure App Service
> 💄 Remove Dashes in Skill Names

- src/components/profile-list/profile-list.js
Relates to https://github.com/SSWConsulting/SSW.People/issues/634
Only display selected skill text once:
> 💄 Update to display filtered skill name only once

- .github/workflows/template-build.yml
https://github.com/SSWConsulting/SSW.Website/issues/2833
> Events - get WEBSITE_API var into app

- gatsby-node.js
- package.json
- yarn.lock
Part of https://github.com/SSWConsulting/SSW.Website/issues/1080
Adds new routes for SSW.Website to use to fetch data easily.
Adds `/people.json`, a filtered JSON list of non-Alumni people. For which `{{ PERSON }}/profile.md` is generated. 
Adds to the page generation to generate `{{ PERSON }}/profile.md` for each non-Alumni person. Which will be used by SSW.Website.
> ✨ Publish profile data as a .md file

- site-config.js
cc @wicksipedia
as per @adamcogan 's email: SSW.Rules | “Star us”
> Added extra words to SSW.People title

- gatsby-node.js
- site-config.js
- src/components/footer/footer.js
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/pages/404.js
Just searched and fixed all the urls
> Change url from ssw.com.au to www.ssw.com.au

- package.json
- yarn.lock
I Updated the megamenu to use the latest version. I also checked that the mobile layout is working correctly. ~~so if anything goes wrong the captain goes down with the ship.~~
**Figure**: **megamenu with updated contrast on SSW People**
> 💄Megamenu - Updated version to latest

- gatsby-node.js
@amankumarrr and I did this together
Also added the position field
SSWConsulting/SSW.Website#3087
> Profile sync - Fix bugs with Markdown sanitizing

- package.json
- yarn.lock
Issue: https://github.com/SSWConsulting/SSW.Rules/issues/1438
Updated ssw.rules.widget package to 2.0.5 version
> ♻️ Updated widget package to new version

- src/templates/person.js
> ♻️ Limited widget rules count to 5

- src/templates/person.js
As per my conversation with Caleb, missed one change from #684
https://github.com/SSWConsulting/SSW.People/issues/683
> Hide alumni links v2

- gatsby-node.js
> Use consts

- src/components/head/head.js
Closes #682 
Updated broken links that were pointing to the old VM
> 🔗 Updated pigeon links in head.js

- gatsby-browser.js
- package.json
- src/style.css
- yarn.lock
As per #697, this PR updates the fontset from Open Sans to Inter
> Change the fontset from open sans to inter

- src/components/profile-utils/profile-photo-utils.jsx
- src/components/profile-utils/utils/CopyProfileInformation.jsx
- src/components/withLocation/withURLLocation.js
Fixes: #692 
- Source URL of the photo was undefined after copying details and in the end causing to not render the photo on the table
- Fixed undefined issue, and renamed variables
- Fixed `location` eslint issue as it was blocking me to test changes in locally
**Figure: Photo is copied to email body with the details successfully**
> Fixed photo wasn't being copied with details

- package.json
- yarn.lock
Updates the megamenu to the latest version
**Figure**: **Megamenu sidebar with latest videos icon**
> updated megamenu to the latest version

- .github/ISSUE_TEMPLATE/0-feature.md
- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/2-docs.md
- .github/ISSUE_TEMPLATE/3-refactor.md
- .github/ISSUE_TEMPLATE/4-devops.md
Adding GitHub Issue Templates to SSW.People as per rule https://www.ssw.com.au/rules/github-issue-templates/
> Adding GitHub Issue Templates

- src/pages/alumni/index.js
Fixes #714 
**Figure: Current Alumni page - https://www.ssw.com.au/people/alumni/**
**Figure: Fixed Images**
> Fixed the alumni page images

- package.json
- yarn.lock
CC: @tiagov8 
Releasing tiago's changes 
https://github.com/SSWConsulting/SSW.MegaMenu/pull/120
> bumped megamenu version

- package.json
- src/components/footer/footer.js
- yarn.lock
#663
This PR makes the footer the same as SSW rules. It includes a GitHub start button and a TinaCMS link.
> 💄 Footer - Add GitHub star button and Tina link

- package.json
- yarn.lock
**Fixes** https://github.com/SSWConsulting/SSW.MegaMenu/issues/99
> bumped megamenu version to 4.11.0
